### ISSUE TITLE
load csv as Array

### ISSUE THREAD

**Issue by lluis** [tilo/smarter_csv#101]
Can a CSV be loaded as an Array instead of a Hash?

so this csv:

    First Name,Last Name,Dogs,Cats,Birds,Fish
    Dan,McAllister,2,0,,
    Lucy,Laweless,,5,0,
    ,,,,,
    Miles,O'Brian,0,0,0,21
    Nancy,Homes,2,0,1,
    Hernán,Curaçon,3,0,0,
    ,,,,,

is loaded as this Array:

    [
      ["First Name", "Last Name", "Dogs", "Cats", "Birds", "Fish"],
      ["Dan", "McAllister", "2", "0"],
      ["Lucy", "Laweless", "", "5", "0"],
      [],
      ["Miles", "O'Brian", "0", "0", "0", "21"],
      ["Nancy", "Homes", "2", "0", "1", ""],
      ["Hernán", "Curaçon", "3", "0", "0"],
      []
    ]

if not, do you think this is a useful functionality?

**Comment by tilo** [comment]
`smarter_csv` was specifically designed to load records as hashes, so the data can be consumed more easily.
