### ISSUE TITLE
Encoding::UndefinedConversionError: "\x87V" from Shift_JIS to UTF-8 issuse

### ISSUE THREAD

**Issue by duongnv-0312** [tilo/smarter_csv#105]
I get the exception
 **Encoding::UndefinedConversionError: "\x87V" from Shift_JIS to UTF-8 issuse**
`from ../smarter_csv.rb:254:in `each_char'`.
 when I try to process CSV with encoding SHIFT_JS.
I try to filter out the invalid byte sequence first and then process it with smarter CSV but ...
```
handler = open(file.path)
csv_string = handler.read.encode!('UTF-8', 'utf-8', invalid: :replace)
CSV.parse(csv_string)
```
How can I fix it?
Thanks in advance.

**Comment by tilo** [comment]
can you try it with version 1.1.5 ?

**Comment by tilo** [comment]
@oNgoVanDuong 
is this fixed with 1.1.5 for you? 
If not, please let me know and provide a sample CSV file

**Comment by fruwe** [comment]
@oNgoVanDuong Just an idea, but did you try CP932 instead of Shift JIS, because it contains important characters, which are not included in the standard Shift JIS

**Comment by tilo** [comment]
@duongnv-0312 is this resolved?

**Comment by tilo** [comment]
closing stale issue - no response
