### ISSUE TITLE
not strip whitespace in column 

### ISSUE THREAD

**Issue by mhi20** [tilo/smarter_csv#106]
This Initialize Class SmarterCSV : 
data = SmarterCSV.process(file,strip_whitespace:true)
output : 
{:﻿ f_name=>"test1", :l_name=>"test2"}
problem here: 
whitespace in ": f_name"
without utf8 character is : 
{:"\xEF\xBB\xBFf_name"=>blah blah}
problem just is  one part in record but other parts do worked !
example : 
student[:f_name] => nil   
but 
student[:l_name]=> blah blah
Can anyone help me ?

**Comment by tilo** [comment]
try to use version 1.1.5
