### ISSUE TITLE
A field with 'options_trader' is truncated to 'trader'

### ISSUE THREAD

**Issue by enviable** [tilo/smarter_csv#115]
Any field that matches 'options' and then any of the set [:quote_char] is truncated from the field due to the improper interpolation.
Correcting the interpolation causes the quotation tests to fail.

PR #71 removes the broken lines as @colinpetruno tested them and found them to be unnecessary.
Here's a fork with the [failing test](https://github.com/enviable/smarter_csv/tree/line_containing_option_is_truncated)

**Comment by tilo** [comment]
PR #71 is closed - the tests were added to 1.2.0 and 2.0.0 -- no code-changes were needed to make it work. 

I'll add a separate test for the case you mentioned `options_trader`.

**Comment by tilo** [comment]
can not reproduce

**Comment by enviable** [comment]
This is still an issue. Here's where it breaks: 
![screen shot 2018-01-25 at 10 10 44 am](https://user-images.githubusercontent.com/870808/35398701-2d9f67f0-01b8-11e8-9bfa-017723c1191f.png)
