### ISSUE TITLE
Field with 'options_trader' is read as 'trader'

### ISSUE THREAD

**Issue by enviable** [tilo/smarter_csv#119]
![screen shot 2018-01-25 at 10 10 44 am](https://user-images.githubusercontent.com/870808/35398851-81d666a2-01b8-11e8-8046-54596714a0bd.png)

**Comment by tilo** [comment]
can you provide a test which reproduces this issue?

**Comment by tilo** [comment]
@enviable Josh, please use the just released version 1.2.1 
Thank you for reporting!

**Comment by tilo** [comment]
@enviable  Josh, please check version 1.2.2
