### ISSUE TITLE
Skip file opening, allow reading from csv string

### ISSUE THREAD

**Issue by waruboy** [tilo/smarter_csv#120]
Hi Tilo! I'm reviewing the 2.0 version. Nice rewrite!

With the additional flexibility, I'm wondering if you can add support to just process a huge csv string.
Use case: We download our csv from amazon s3 and have it ready on memory. Would be nice if we can just feed it to smarterCSV ala CSV.parse()

**Comment by tilo** [comment]
I'll look into it

**Comment by waruboy** [comment]
Ah, our csv is only in tens of MB, so it's too large to process in-request, but still ok for in-memory processing.
I agree that we might need to do streaming in the future though, so thanks for pointing me to the resource

**Comment by tilo** [comment]
ear-marked for v2.0
