### ISSUE TITLE
[Question] Memory not freeing up

### ISSUE THREAD

**Issue by arvryna** [tilo/smarter_csv#123]
Guys, 

1) In rails console i have loaded a CSV with 100k rows as `z = SmarterCSV.process(path, options)` , it occupied around 1GB in memory.
`options = {:chunk_size=>500, :remove_zero_values=>false, :remove_empty_values=>false, :file_encoding=>"ISO-8859-1"}
`
then i set z=nil, that 1GB is not freed.  why is that ? will the same happen if i run the code in prod machine ?

2) Why is chunk_size = 500 not working in this case ? 
 if i inspect the variable `z` as set above i'm getting around 500x220 records , ie the entire 100k is loaded in memory.

Am i using smarterCSV incorrectly ?

i use version '1.1.0'

**Comment by aravinth-chandran** [comment]
Any updates on this ?

**Comment by arvchz** [comment]
Any updates on this @tilo  ?

**Comment by KevinColemanInc** [comment]
@arvchz 

Maybe this could be related?
https://github.com/tilo/smarter_csv/issues/135

**Comment by ThePeiggy** [comment]
I'm encountering the same issue. Memory leak from loading 1GB CSVs, causing a lot of headaches in production.

**Comment by arvchz** [comment]
@ThePeiggy : Which version are you using ?
