### ISSUE TITLE
Yield raw CSV line

### ISSUE THREAD

**Issue by piacsek** [tilo/smarter_csv#127]
Smarter CSV could yield the unparsed content of each line it processes. My application needs the raw data for logging purposes.

**Comment by tilo** [comment]
can you please submit a PR?
Is this for version 1.x or 2.x?

**Comment by FelipePiacsek** [comment]
Hey. It is for version 2. I'll submit the PR tomorrow! Thanks!

**Comment by tilo** [comment]
I left a comment on the PR - I think this will negatively affect the memory utilisation for large CSV files.
