### ISSUE TITLE
Collect all Errors, before surfacing them. Avoid throwing an exception on the first error.

### ISSUE THREAD

**Issue by KevinColemanInc** [tilo/smarter_csv#133]
If there are failures in parsing the CSV, it will be a better user experience if all of the errors can be captured instead of throwing an exception on the first error.

For example, if you have 2 missing columns and 2 duplicate columns, smarter_csv will stop after finding the missing columns instead of also reporting the duplicate columns.

**Comment by tilo** [comment]
ear-marked for v2.0
