### ISSUE TITLE
potential memory leak in csv

### ISSUE THREAD

**Issue by KevinColemanInc** [tilo/smarter_csv#135]
If someone uploads a CSV with a massively long title, smarter_csv calls `to_sym` on the long title.  Since symbols are never cleaned up, the memory is retained.

For reasonably large titles, to_sym makes sense, because you don't want to have all of these strings allocated in memory.

I know you can explicitly ask smarter_csv to use strings as keys, but I wonder if there could be a middle ground where large headers are never symbolized or if the string titles could have their own object cache that can get cleaned up later by the GC.

https://github.com/tilo/smarter_csv/blob/1.2-stable/lib/smarter_csv/smarter_csv.rb#L87

thoughts?

**Comment by aravinth-chandran** [comment]
I have reported a similar error here => https://github.com/tilo/smarter_csv/issues/123#issuecomment-383822312

**Comment by BrianHawley** [comment]
"Since symbols are never cleaned up, the memory is retained."

This is no longer true starting with Ruby 2.1. Symbols and frozen strings are collected by the GC.

**Comment by KevinColemanInc** [comment]
I stand corrected! thanks. I am closing the issue.
