### ISSUE TITLE
Default comment_regexp option incorrectly matches '#' characters after start of lines when used with non-default `row_sep`.

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [tilo/smarter_csv#136]
Consider a CSV with the following contents:

`h1,h2\r\n1,"b\n#c"`

With `row_sep: "\r\n"` this should be parsed as:
```
[{
  h1: "a",
  h2: "b\n#c",
}]
```

But the default `comment_regexp`, `/^#/`, matches the `\n#` in the the second row of the CSV and the row is ignored entirely. (Because `$/` is set to `"\r\n"`, the [first `f.readline`](https://github.com/tilo/smarter_csv/blob/master/lib/smarter_csv/smarter_csv.rb#L170) reads the entire rest of the file, not just `"b"`.)

The correct regexp should be `/\A#/`, though, comments are definitely not part of any CSV specification, so `comment_regexp` should really default to `nil`.

**Comment by tilo** [comment]
thank you for the bug report!

**Comment by tilo** [comment]
fixed in 1.2.5
