### ISSUE TITLE
Exceptions shouldn't be under "Exception"

### ISSUE THREAD

**Issue by Hengjie** [tilo/smarter_csv#137]
The design of the exceptions should really be under `StandardError` and we should be creating our own `SmarterCSVException` class that extends from `StandardError` and every other exception should be a class that extends from `SmarterCSVException`

See the bit from "The Class Hierarchy" and below http://blog.honeybadger.io/a-beginner-s-guide-to-exceptions-in-ruby/

**Comment by tilo** [comment]
agreed! will fix
