### ISSUE TITLE
`required_headers` does not define required headers

### ISSUE THREAD

**Issue by KevinColemanInc** [tilo/smarter_csv#140]
`key_mapping` contains a list of csv headers mapped to attribute names.

`required_headers` is actually expected to contain a list of attribute names, not csv headers. 

For example, lets say a csv has 1 required column in it with the header of "name".  You need the attribute to be mapped to "full_name", because that is what you called it in your model.  Your `key_mapping` would look like this:

```
{
  "name" => "full_name"
}
```

The csv header would be "name" and if you wanted to require name, I would think you would need to set `required_headers = ["name"]` not `["full_name"]`, since the header as the user sees it is is `"user"`.

Unfortunately, currently, `required_headers` really is `required_attribute_names` or something along those lines.

**Comment by camiloforero** [comment]
I also found this issue. Are there plans to fix it in v2? It looks like required_headers validations should run before the fields are mapped with key_mapping

**Comment by tilo** [comment]
yes, it looks like a misnomer. will have a look

**Comment by tilo** [comment]
improved README and added tests to demonstrate the expected behavior (version 1.8.1)

**Comment by tilo** [comment]
@camiloforero @KevinColemanInc will be renamed `required_keys` in version 1.8.1
