### ISSUE TITLE
GPL or MIT licence, not "and"

### ISSUE THREAD

**Issue by ptrippett** [tilo/smarter_csv#154]
Hi,

I have a picky client and need to clarify the licensing, is it "MIT and GPL-2" or "MIT or GPL-2".

Thanks
Paul

**Comment by ramarnat** [comment]
Likewise. Could you clarify the licensing model?

**Comment by B1aine** [comment]
Hi,

First of all, appreciate your work, thank you!

Bumping the question(s) above, we would be very grateful if you could please provide info whether we are free to choose which license to use or they have to be used jointly.

Thanks,
RC

**Comment by tilo** [comment]
you can pick which of the licenses listed in the gemspec file you want to use - only the license you picked is applicable to you.

**Comment by B1aine** [comment]
Thank you! Much appreciated Tilo

Cheers,
RC

**Comment by tilo** [comment]
I also clarified it in the gemspec file - should be pushed out with the next version 

https://github.com/tilo/smarter_csv/blob/8544e7f9760d2b7387a8fdf4658f1adb46f5c0a4/smarter_csv.gemspec#L18
