### ISSUE TITLE
Header keys not matching

### ISSUE THREAD

**Issue by SimonBrazell** [tilo/smarter_csv#155]
I'm using this library to do a bulk import of property data and I've come across this strange issue, for some reason the first header key is not matching when I try to retrieve it's value, only the first, all others work as expected, see below:
 
```
2.7.0 :001 > csv = SmarterCSV.process('/Users/sbrazell/Desktop/properties.csv')
2.7.0 :002 > row = csv.first
2.7.0 :003 > row
 => {:assessment_number=>100100364, :house_number=>4, ... }
2.7.0 :004 > row[:assessment_number]
 => nil # Should be 100100364
2.7.0 :005 > row[:house_number]
 => 4
```

Any ideas? Note I tried using ruby `2.6.3` prior to updating to `2.7.0` results were the same.

**Comment by vinni101** [comment]
Hi @SimonBrazell were you able to get this issue resolved. I am experiencing a similar issue.

```
[71] pry(main)> items = SmarterCSV.process('tmp/hummuch.csv')
=> [ {
 {:﻿brand=>"Tanimura & Antle", :item=>"Iceburg Lettuce", :price=>"4.99"},
 {:item=>"Cabbage", :price=>"7.27", :unit=>"kg"},
 {:item=>"Raisins", :price=>"14.62", :unit=>"kg"}]
[72] pry(main)> items.first[:brand]
=> nil
```

**Comment by SimonBrazell** [comment]
Hi @vinni101 , I did the following in my import task, not ideal but works for now:

```ruby
SmarterCSV.process(csv, options) do |chunk|
          chunk.each do |row|
              assessment_number = row.first[0] =~ /assessment_number/ ? row.first[1] : ''
              # where row.first[0] is column header, row.first[1] is column value.
          end
end
```
So I just check that the header in column 1 matches the column I'm after (as users could submit the CSV in the wrong format) and assign the value if it is, blank if not.

**Comment by vinni101** [comment]
Hi @SimonBrazell I appreciate the quick response. I implement the work around you suggested and it worked fine.

Thanks a mil

**Comment by tilo** [comment]
can not reproduce this 🤔 

are you passing in a filename, or a filehandle?
any control characters on or before the first data line?

**Comment by SimonBrazell** [comment]
Hi @tilo! I stopped using this library since then so can't confirm the behaviour now.

If you look at my original issue though you'll see that I was passing the filename.

[Here](https://github.com/tilo/smarter_csv/files/8020265/Test.csv) is an example of what I would have used back then, if that doesn't help perhaps @vinni101 can provide something?

**Comment by tilo** [comment]
Hmm.. I can't reproduce it:

```
data = SmarterCSV.process('Test.csv')
row = data.first
row[:asessment_number]
 => 123456
 ```

**Comment by tilo** [comment]
can not reproduce
