### ISSUE TITLE
SmartSCV process of large CSV files from Amazon S3

### ISSUE THREAD

**Issue by resistorsoftware** [tilo/smarter_csv#156]
I have a large 200MB CSV file in Amazon S3 storage. I download it using Fog AWS and then process it using SmarterCSV.process method. 

Thing is, when I download the file, I save it as a tempfile so I can use it, but that blows up my Heroku Dyno in terms of memory usage. So I would love to see a way where I can download the CSV in chunks and process it. All my attempts have ended in failure with various errors from Smarter CSV about closing files, and in general, it just does not want to work. Ideally, I would love to parse the CSV, and not bog down the Dyno with a 200MB+ file. 

Are there any examples out there of using SmarterCSV and not chewing up tons of memory? I cannot seem to find any good examples in the wild. Claims are there that it works, but without some examples, I am not sure what to do, short of taking apart the whole process method myself.

**Comment by espen** [comment]
Have you tried setting chunk_size so the entire file is not loaded into memory?

**Comment by resistorsoftware** [comment]
Yes, I learned how to use chunks. For the most part that works well. Still, I have run into many problems with CSV processing beyond the size issue. Mostly due to how terrible most people construct CSV files in the first place.
