### ISSUE TITLE
convert_to_float saves Proc as @@convert_to_integer

### ISSUE THREAD

**Issue by anthonyjlower** [tilo/smarter_csv#157]
https://github.com/tilo/smarter_csv/blob/master/lib/smarter_csv/hash_transformations.rb#L88

It looks like the proc is being saved as the wrong name so line 94 returns a `NameError: uninitialized class variable @@convert_to_float in SmarterCSV` error.

**Comment by tilo** [comment]
note: code moved to 2.0 branch

**Comment by tilo** [comment]
Ear-marked for 2.0
