### ISSUE TITLE
Is there any way to check if the row is the last line while parsing

### ISSUE THREAD

**Issue by ghost** [tilo/smarter_csv#159]
I am using this gem to parse a large CSV file.
This is the code I am using.
```
SmarterCSV.process(file_name, { chunk_size: 10, headers_in_file: false, user_provided_headers: user_provided_headers }) do |chunk|
    chunk.each do |row|
      # parse row
    end
  end
```

Is there any way to check if the row is last line?

**Comment by tilo** [comment]
basically no, unless you know in advance how many lines there are in the CSV file.

You only know that the previous line was the last line, once you try to fetch the next line and get an EOF error
