### ISSUE TITLE
Update & tag pre-release branch

### ISSUE THREAD

**Issue by bigzoo** [tilo/smarter_csv#176]
Hi @tilo,

Thanks for all the work you've done on smarter_csv, big fan!.

I'd like to request for a new pre-release branch with the latest changes in master (2.0.0.pre1 is quite outdated); and if it can be tagged as well even though still being pre-release, it would make it so much easier to use the new changes in a project.

Happy to collaborate on this 🙏🏽 .

Best,
Chris

**Comment by agarie** [comment]
@tilo This would be lovely. I can collaborate too. :)

**Comment by tilo** [comment]
I updated the branches a few days ago:

 master -> no longer used
 1.x-stable -> main (new default branch)
 2.0-develop : updated
 2.0.0.pre2 : updated (not much change yet)

@bigzoo @agarie email me

**Comment by bigzoo** [comment]
> I updated the branches a few days ago:
> 
> master -> no longer used 1.x-stable -> main (new default branch) 2.0-develop : updated 2.0.0.pre2 : updated (not much change yet)
> 
> @bigzoo @agarie email me

Awesome news @tilo, I'll contact you for collaboration.
