### ISSUE TITLE
Missing LICENSE file in repo/gem

### ISSUE THREAD

**Issue by marvinthepa** [tilo/smarter_csv#180]
The gemspec mentions that it is MIT/GPL-2 licensed, but the repo does not contain a License file.

Would be nice to include one. AFAIK a license needs a "Copyright $YEAR $HACKER" line to be valid, which is difficult to generate correctly if you only have the info from the gemspec..

Would be also nice if the License file was included in the gem.

**Comment by tilo** [comment]
will fix

**Comment by tilo** [comment]
fixed in 1.4.0
