### ISSUE TITLE
v1.2.9 is a breaking change

### ISSUE THREAD

**Issue by daslicious** [tilo/smarter_csv#182]
Many thanks for the great gem!

Just a heads up that apps that expect the keys to be symbols might break with 1.2.9.

https://github.com/tilo/smarter_csv/commit/7d71b3fa1a1f0ba5a21ae9379fc05de29704d191

**Comment by hknaksu** [comment]
I got a broken app and 1.2.6 & 8 no longer returns the keys as symbols either!

**Comment by tilo** [comment]
oh my :(

**Comment by tilo** [comment]
@daslicious @hknaksu do you have a test case for this?

**Comment by tilo** [comment]
@daslicious @hknaksu This was fixing a bug, and should have been version 1.3.0, not 1.2.9

Yes, it is a breaking change, but easy to fix:

if you use `--key_mappings`, please change your code:
     * either use symbols in the `key_mapping` hash
     * or change the expected keys from symbols to strings

**Comment by tilo** [comment]
https://twitter.com/tilosloboda/status/1490503228030537728?s=20&t=4Ti8YCaFcZvRpBASiql07Q
