### ISSUE TITLE
Feature Request: Date Parsing

### ISSUE THREAD

**Issue by agaviria** [tilo/smarter_csv#2]
I've been playing with this gem and it seems quite useful.  However, is there any way to parse a date format? (e.g. mm/dd/yyyy)  It is currently converting it into a string that does not resemble a date. (e.g. \\\"$266\")

**Comment by xufeiyun** [comment]
Why does this request not implemented for a long period?
I think it will also be ok if #41 is released, thus user is able to handle the parser by himself temporary.

**Comment by tilo** [comment]
was too busy at work  :P

implemented in 1.1.0
