### ISSUE TITLE
Way to ignore all non-mapped keys?

### ISSUE THREAD

**Issue by DaveSanders** [tilo/smarter_csv#21]
First off, thanks for such a useful library.

Second, is there an option I'm missing to ignore any columns in the file if I did NOT map the key?

So, if there were 4 columns A,B,C,D and I only mapped A,C, then the chunk would only contain h[:a] and h[:c].

If not, then that'd be a definite useful feature, especially if you are importing the rows into a database where they blow up if fields are presented that don't exist.

If I get time I might try to fork and add this, but I wanted to make sure I wasn't missing an option somewhere.

**Comment by tilo** [comment]
@netwire88 in that case, you would have to provide user_defined_headers and then can map the unwanted field to nil
