### ISSUE TITLE
cannot load such file -- smarter_csv.bundle (LoadError)

### ISSUE THREAD

**Issue by hknaksu** [tilo/smarter_csv#234]
1.8.3 breaks on Darwin.

here's the error:
ruby-3.1.3/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- smarter_csv.bundle (LoadError)
	from /Users/mha/.rvm/gems/ruby-3.1.3/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/mha/.rvm/gems/ruby-3.1.3/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/mha/.rvm/gems/ruby-3.1.3/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `require'
	from /Users/mha/.rvm/gems/ruby-3.1.3/gems/smarter_csv-1.8.3/lib/smarter_csv.rb:7:in `<top (required)>'

here's the diff v1.83 vs v1.8.2 for lib/smarter_csv.rb
6,10c6,7
```
< if `uname -s`.chomp == 'Darwin'
<   require 'smarter_csv.bundle' unless ENV['CI'] # local testing
< else
<   require_relative "smarter_csv/smarter_csv" unless ENV['CI'] # does not compile/link in CI?
< end
---
> require_relative "smarter_csv/smarter_csv" unless ENV['CI'] # does not compile/link in CI?
> # require 'smarter_csv.bundle' unless ENV['CI'] # local testing
417c414
<         return ',' if line.chomp(options[:row_sep]) =~ /^\w+$/
---
>         return ',' if line =~ /^\w+$/
```

**Comment by key88sf** [comment]
Same issue here. Darwin  arm64  (Macbook Pro running Ventura 13.2.1).

**Comment by renzodiaz** [comment]
Same issue here! Macbook Pro Ventura 13.1.

**Comment by stevenhaddox** [comment]
Same issue here on a Mac Studio M1 Max on Ventura 13.3. Locking to version `1.8.2` resolves the issue.

**Comment by tilo** [comment]
@hknaksu @key88sf @renzodiaz @stevenhaddox 1.8.4 will fix this
