### ISSUE TITLE
[1.9.1] cannot load such file -- smarter_csv.bundle (LoadError) 

### ISSUE THREAD

**Issue by PikachuEXE** [tilo/smarter_csv#249]
Same as https://github.com/tilo/smarter_csv/issues/234

**Comment by courtsimas** [comment]
Same. It's no longer functioning.

**Comment by tilo** [comment]
@PikachuEXE @courtsimas what OS version are you on?
Do you have the XCode toolchain installed? 🤔 

very odd - I tried it out before releasing this version, and it worked on my M1 Mac running 14.0 

Please help me reproduce this issue. 

I pulled 1.9.1 for now

**Comment by courtsimas** [comment]
macOS 14.1 on latest intel. 2019 MBP. And yes Xcode toolchain is installed.

**Comment by PikachuEXE** [comment]
MacOS 13.6.1 (22G313) M1 Mac Xcode installed (I use homebrew so it must be installed)

Error:
```
# require "smarter_csv"

LoadError: cannot load such file -- smarter_csv.bundle
from <internal:/Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
Caused by LoadError: cannot load such file -- /Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/smarter_csv-1.9.1/3.2.2/smarter_csv
from /Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/smarter_csv-1.9.1/lib/smarter_csv.rb:14:in `require_relative'
```

**Comment by tilo** [comment]
interesting! looks like you're using `asdf`, whereas I'm using `rvm` to install ruby and gems.

**Comment by tilo** [comment]
@courtsimas what are you using to install Ruby and gems? `asdf`, `rvm`, or something else?

**Comment by courtsimas** [comment]
> @courtsimas what are you using to install Ruby and gems? `asdf`, `rvm`, or something else?

Rbenv

**Comment by n-rodriguez** [comment]
Hi there! I have the same issue here with `asdf` but I don't think it's related.

Actually the `smarter_csv.bundle` file do exist :

```sh
nicolas@MacBook-Pro-de-Nicolas:~/PROJECTS/CONCERTO/concerto/.bundle/ruby/3.2.0/gems/smarter_csv-1.9.1$ tree .
.
├── CHANGELOG.md
├── CONTRIBUTORS.md
├── Gemfile
├── LICENSE.txt
├── README.md
├── Rakefile
├── TO_DO_v2.md
├── ext
│   └── smarter_csv
│       ├── Makefile
│       ├── extconf.rb
│       └── smarter_csv.c
├── lib
│   ├── core_ext
│   │   └── hash.rb
│   ├── smarter_csv
│   │   ├── options_processing.rb
│   │   ├── smarter_csv.bundle
│   │   ├── smarter_csv.rb
│   │   └── version.rb
│   └── smarter_csv.rb
└── smarter_csv.gemspec
```

I've changed this `require` https://github.com/tilo/smarter_csv/blob/e7ef9a351fef3d5cabd6df3564b27cdc25343ae2/lib/smarter_csv.rb#L19 to `require 'smarter_csv/smarter_csv.bundle'` and it works 😃

**Comment by tilo** [comment]
thank you @n-rodriguez !

**Comment by PikachuEXE** [comment]
Let me know if you want to us to test (even just a branch) when ready

**Comment by tilo** [comment]
@n-rodriguez @courtsimas can you try to install `1.9.2.pre01`? 

`gem install --prerelease smarter_csv`

Please let me know if that works, and if `SmarterCSV.has_acceleration?` is `true`?

**Comment by n-rodriguez** [comment]
MacOS 14.1.1 + M2 seems fine

```sh
irb(main):001> require 'smarter_csv'
=> true
irb(main):002> SmarterCSV.has_acceleration?
=> true
irb(main):003> SmarterCSV::VERSION
=> "1.9.2.pre01"
```

**Comment by tilo** [comment]
thank you!🙇‍♂️
releasing 1.9.2 now
