### ISSUE TITLE
Link on readme not accessible

### ISSUE THREAD

**Issue by zoras** [tilo/smarter_csv#251]
The url link to page http://www.unixgods.org/~tilo/ruby/process_csv_as_hashes.html on the project's readme https://github.com/tilo/smarter_csv#see-also is not accessible anymore.

It returns

```nginx
404 Not Found
nginx/1.2.6
```

**Comment by tilo** [comment]
thank you for letting me know! 👀

**Comment by tilo** [comment]
@zoras it is fixed in 1.10.3

the link is:
  http://www.unixgods.org/~tilo/Ruby/process_csv_as_hashes.html
