### ISSUE TITLE
Problem when installing Gem

### ISSUE THREAD

**Issue by widjajayd** [tilo/smarter_csv#253]
gem install smarter_csv

ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://index.rubygems.org/quick/Marshal.4.8/smarter_csv-1.9.1.gemspec.rz)

**Comment by tilo** [comment]
Version 1.9.1 was yanked, because of some installation issues on MacOS.

It was no major change in behavior - please just use 1.9.0 for now

**Comment by widjajayd** [comment]
back using 1.9.0 running well,

gem 'smarter_csv', '1.9.0'

**Comment by tilo** [comment]
@widjajayd version 1.9.2 is being released today
