### ISSUE TITLE
smarter_csv 1.9.1 is yanked but eco-system and changelog do not acknowledge (yet)

### ISSUE THREAD

**Issue by btihen** [tilo/smarter_csv#254]
Today I was trying to update our code after doing a bundle outdated:

```
$ bundle outdated --minor

Gem                Current   Latest   Requested  Groups
smarter_csv   1.9.0        1.9.1       >= 0           default
```

and was getting errors from rubygems:

```
Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to
underlying error <bad response Forbidden 403
(https://rubygems.org/gems/smarter_csv-1.9.1.gem)>
```

when I checked the webpage: https://rubygems.org/gems/smarter_csv/versions

v1.9.1 is listed as yanked.

It might be helpful to update your changelog and let `bundle outdated` know (I am not familiar with the process).

**Comment by gammons** [comment]
yeah, right now any bundle installs using this gem are failing because it's looking for v1.9.1 and getting a 403 response.  You have to explicitly ask for v1.9.0.  Just a heads up

**Comment by tilo** [comment]
I updated the CHANGELOG. Working on `1.9.2`

**Comment by tilo** [comment]
@gammons version 1.9.2 is being released today

**Comment by btihen** [comment]
Perfect - thanks!

**Comment by Nakilon** [comment]
I still haven't understood why `gem install` was trying to install yanked version.

**Comment by gammons** [comment]
Thanks all!  `bundle install` works correctly now for the latest 1.9.2 version.

**Comment by gammons** [comment]
Also, the DKIM selector I used is called "google".
