### ISSUE TITLE
UTF-8 with BOM (character 65279 at file start)

### ISSUE THREAD

**Issue by kaligrafy** [tilo/smarter_csv#27]
I was having weird problems when reading keys from a smarter_csv parsed csv file:
the first key was never recognize. After a long time I tought maybe the file had a special character in it and then: boom! i found the csv file was in UTF-8 with BOM, and there was a Unicode Character 'ZERO WIDTH NO-BREAK SPACE' (U+FEFF) (#65279) as the first character, so the first key always had this character at index [0] and nobody could see it...

Could you ignore BOM and delete this character if first line starts with it when reading the csv file? Thanks!

You could do this: 

```
content = File.open('file.txt', "r:bom|utf-8")
content[0] = "" if content.start_with?(["FEFF".to_i(16)].pack("U"))
```

**Comment by ajw725** [comment]
@tilo i realize this is four years old, and your workaround works for me, but this does not seem to be a corner case. i'm seeing it now with any CSV generated by Excel on Windows.

**Comment by kaligrafy** [comment]
OK, thanks! Feel free to add the workaround if you think it could be useful.

**Comment by ajw725** [comment]
as @tilo described / using his example:

without the workaround:
```ruby
data = SmarterCSV.process('trips.txt')

data.first
=> {:route_id=>1, :service_id=>"13N_S", :trip_id=>"13N_13N_S_1_1_0.22917", :trip_headsign=>"Station Honoré-Beaugrand"}

data.first[:route_id]
=> nil

data.first.keys.first.to_s.chars
=> ["", "r", "o", ...]
```

with the workaround:
```ruby
data = nil
File.open('trips.txt', 'r:bom|utf-8') { |f| data = SmarterCSV.process(f) }

data.first
=> {:route_id=>1, :service_id=>"13N_S", :trip_id=>"13N_13N_S_1_1_0.22917", :trip_headsign=>"Station Honoré-Beaugrand"}

data.first[:route_id]
=> 1

data.first.keys.first.to_s.chars
=> ["r", "o", ...]
```

**Comment by 9mm** [comment]
Shouldnt a smarter CSV library handle this automatically? I can't open any CSV thats been exported by excel because these are all the column headers:

<img width="157" alt="image" src="https://user-images.githubusercontent.com/1386207/158081871-0eb6b53c-87a4-41ea-9b3a-7948ce421634.png">

On top of that, look at what it parses for the partner_id:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1386207/158081876-46574ef9-52da-4c72-a42d-625a665bce28.png">

**Comment by 9mm** [comment]
This is definitely not a corner case, considering BOM are the bane of working with CSV's, and excel is the most popular CSV program. This being handled within the gem seems like a no brainer

**Comment by tilo** [comment]
```
$ hexdump -C /tmp/bom-issue.csv
00000000  ef bb bf 73 6f 6d 65 5f  69 64 2c 74 79 70 65 2c  |...some_id,type,|
00000010  66 75 7a 7a 62 6f 78 65  73 0d 0a 34 32 37 36 36  |fuzzboxes..42766|
00000020  38 30 35 2c 7a 69 7a 7a  6c 65 73 2c 31 32 33 34  |805,zizzles,1234|
00000030  0d 0a 33 38 37 35 39 31  35 30 2c 71 75 69 7a 7a  |..38759150,quizz|
00000040  65 73 2c 35 36 37 38 0d  0a                       |es,5678..|
```

**Comment by tilo** [comment]
fixed in https://github.com/tilo/smarter_csv/pull/220
