### ISSUE TITLE
Unbalanced quote_char does not raise an error

### ISSUE THREAD

**Issue by rex-remind101** [tilo/smarter_csv#283]
Actual output:
```
$ cat cats.csv
first name,last name,dogs,cats,birds,fish
     Dan,McAllister,2,1,"2,4
     Lucy,Laweless,,5,,
     Miles,O'Brian,,,,21
     Nancy,Homes,2,,1,

x = SmarterCSV.process('/Users/Me/Documents/parentsquare/parent_square/cats.csv', options: {verbose: true})
EOFError: end of file reached
from /Users/Me/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/smarter_csv-1.2.8/lib/smarter_csv/smarter_csv.rb:141:in `readline'
```
Expected output:
`EOFError: end of file reached on line 1` (assumes 0 counting)

**Comment by rex-remind101** [comment]
I appeared to be on an older version but now i'm seeing a different issue

Actual output:
```
$ cat cats.csv
first name,last name,dogs,cats,birds,fish
     Dan,McAllister,2,1,2,"4
     Lucy,Laweless "Lawless",,5,,
     Miles,O'Brian,,,,21
     Nancy,Homes,2,,1,

pry(main)> x = SmarterCSV.process('/Users/Me/Documents/parentsquare/parent_square/cats.csv', options: {verbose: true})
=> [{:first_name=>"Dan",
  :last_name=>"McAllister",
  :dogs=>2,
  :cats=>1,
  :birds=>2,
  :fish=>"\"4\n     Lucy,Laweless \"Lawless\",,5,,\n     Miles,O'Brian,,,,21\n     Nancy,Homes,2,,1,"}]
```
Expected output:
`EOFError: end of file reached on line 1` (assumes 0 counting)

**Comment by tilo** [comment]
@rex-remind101 have you seen this in actual CSV data, or is this just a theoretical example?

All the double-quote characters in the input file should be escaped. The file is malformed.

```
require 'smarter_csv'
reader = SmarterCSV::Reader.new('/tmp/cats2.csv')

reader.process
reader
 =>
#<SmarterCSV::Reader:0x00000003027f8c08
 @chunk_count=0,
 @csv_line_count=2,
 @enforce_utf8=false,
 @errors={},
 @file_line_count=5,
 @has_acceleration=true,
 @has_rails=false,
 @headerA=[:first_name, :last_name, :dogs, :cats, :birds, :fish],
 @headers=[:first_name, :last_name, :dogs, :cats, :birds, :fish],
 @input="/tmp/cats2.csv",
 @options=
  {:acceleration=>true,
   :auto_row_sep_chars=>500,
   :chunk_size=>nil,
   :col_sep=>",",
   :comment_regexp=>nil,
   :convert_values_to_numeric=>true,
   :downcase_header=>true,
   :duplicate_header_suffix=>"",
   :file_encoding=>"utf-8",
   :force_simple_split=>false,
   :force_utf8=>false,
   :headers_in_file=>true,
   :invalid_byte_sequence=>"",
   :keep_original_headers=>false,
   :key_mapping=>nil,
   :quote_char=>"\"",
   :remove_empty_hashes=>true,
   :remove_empty_values=>true,
   :remove_unmapped_keys=>false,
   :remove_values_matching=>nil,
   :remove_zero_values=>false,
   :required_headers=>nil,
   :required_keys=>nil,
   :row_sep=>"\n",
   :silence_missing_keys=>false,
   :skip_lines=>nil,
   :strings_as_keys=>false,
   :strip_chars_from_headers=>nil,
   :strip_whitespace=>true,
   :user_provided_headers=>nil,
   :value_converters=>nil,
   :verbose=>false,
   :with_line_numbers=>false},
 @raw_header="first name,last name,dogs,cats,birds,fish\n",
 @result=
  [{:first_name=>"Dan",
    :last_name=>"McAllister",
    :dogs=>2,
    :cats=>1,
    :birds=>2,
    :fish=>"\"4\n     Lucy,Laweless \"Lawless\",,5,,\n     Miles,O'Brian,,,,21\n     Nancy,Homes,2,,1,"}],
 @verbose=false,
 @warnings={}>
 ```

**Comment by tilo** [comment]
@rex-remind101 when the double quote characters are properly escaped, parsing is no problem:

```
 cat  /tmp/cats3.csv
first name,last name,dogs,cats,birds,fish
     Dan,McAllister,2,1,2,\"4
     Lucy,Laweless \"Lawless\",,5,,
     Miles,O'Brian,,,,21
     Nancy,Homes,2,,1,
     
data = SmarterCSV.process('/tmp/cats3.csv')     
ap data
=> 

[
    {
        :first_name => "Dan",
         :last_name => "McAllister",
              :dogs => 2,
              :cats => 1,
             :birds => 2,
              :fish => "\\\"4"
    },
    {
        :first_name => "Lucy",
         :last_name => "Laweless \\\"Lawless\\\"",
              :cats => 5
    },
    {
        :first_name => "Miles",
         :last_name => "O'Brian",
              :fish => 21
    },
    {
        :first_name => "Nancy",
         :last_name => "Homes",
              :dogs => 2,
             :birds => 1
    }
]
```

**Comment by tilo** [comment]
@rex-remind101 if this happens, then the source of your CSV files does not properly escape the double-quote characters!

It is best to fix such an issue at the source, because an unescaped double-quote is not valid.

There is a hacky work around - you can give SmarterCSV the option to set the `quote_char` to something different:

```
 > data = SmarterCSV.process('/tmp/cats.csv', quote_char: '^')
 =>
 [
    {
        :first_name => "Dan",
         :last_name => "McAllister",
              :dogs => 2,
              :cats => 1,
             :birds => "\"2",
              :fish => 4
    },
    {
        :first_name => "Lucy",
         :last_name => "Laweless",
              :cats => 5
    },
    {
        :first_name => "Miles",
         :last_name => "O'Brian",
              :fish => 21
    },
    {
        :first_name => "Nancy",
         :last_name => "Homes",
              :dogs => 2,
             :birds => 1
    }
]

```

**Comment by tilo** [comment]
this should throw an error `SmarterCSV::MalformedCSV : unbalanced quote_char in line 2`

**Comment by randall-coding** [comment]
I'm using the latest version 1.12.1, and instead of an EOF error my code will **hang indefinitely** when given a block.

```
SmarterCSV.process(temp_filename, {col_sep: @col_sep, chunk_size: 1000, headers_in_file: false, user_provided_headers: headers}) do |chunk|
     Rails.logger.info("Sanitizing chunk")
     records = chunk.map { |hash| map_row_to_record(hash.values) }
     Rails.logger.info("Insert_all")
     NdmMedicalClaim.insert_all(records)
     break if i >= 10
     i= i+1 
end
```

Seems to be the same issue because changing the `quote_char` as suggested by @tilo solved the issue.   Hopefully there are no unintended side effects.

**Comment by MattKitmanLabs** [comment]
@randall-coding We are getting this hanging indefinitely issue also.

**Comment by tilo** [comment]
@rex-remind101 @randall-coding @MattKitmanLabs check out the upcoming version 1.13.0, 
it has improved handling of unbalanced unescaped quote_chars.

**Comment by dwieringa** [comment]
> @rex-remind101 have you seen this in actual CSV data, or is this just a theoretical example? What program generated the CSV file you saw in production?
> 
> All the double-quote characters in the input file should be escaped. The file is malformed.

@tilo I ran into this.  I'm trying to import tab-delimited files from a very old and painful database system used in a manufacturing environment.  

Some rows have descriptions which use `"` to indicate inches.  eg `20"`

Is there actually an official spec some place that dictates quotation marks must be matched in tab delimited files?

> It is best to fix such an issue at the source, because an unescaped double-quote is not valid.

It seems like delimited text files have been used forever to share data between different organizations and individuals.  Often the consumer won't have the option to dictate how the files will be or were historically produced.

I think it makes sense to make "smart features" optional.   I see the documentation mentions the option `: force_simple_split ` which appears to allow disabling the `quote_char` feature, but I can't find it anywhere in the code.  Was it removed but left in the documentation?

**Comment by tilo** [comment]
@dwieringa does your CSV file contain double-quote characters for other purposes than inches?
If not, you could just set `quote_char` to be an unused character. 

What happens when you import the CSV into a Google sheet or another spreadsheet -- is it read correctly? (You could then try to re-export it as CSV)

Yes, `force_simple_split` was removed after a bigger refactor. Thank you for letting me know the doc still refers to it. I'll fix that.
