### ISSUE TITLE
Processing Hangs when there is a quotation formatting error on a large file

### ISSUE THREAD

**Issue by simonrentzke** [tilo/smarter_csv#288]
This is tested on `ruby 3.2.2`

This is not a bug per-se, because this is badly formatted csv, but it's tricky to diagnose when it happens on a large file as it just hangs in process.

If you take a large CSV like this:

```csv
id,name,suburb
1,Sibu,"Vredehoek"
2,Shamina,"Howard"s Manus"
3,Ayanda,"Tokai"
... another ~30000 rows
```

And process it, it hangs. 

The reason, I believe, is because all proceeding lines are joined into a single data point. For example running `SmarterCSV.process('./smarter_csv_error.csv') { |rw| puts rw }` on this:

```csv
id,name,suburb
1,Sibu,"Vredehoek"
3,Ayanda,"Tokai"
2,Shamina,"Howard"s Manus"
3,Ayanda,"Tokai"
3,Ayanda,"Tokai"
3,Ayanda,"Tokai"
```

Will result in:
```
{:id=>1, :name=>"Sibu", :suburb=>"Vredehoek"}
{:id=>3, :name=>"Ayanda", :suburb=>"Tokai"}
{:id=>2, :name=>"Shamina", :suburb=>"Howard\"s Manus\"\n3,Ayanda,\"Tokai\"\n3,Ayanda,\"Tokai\"\n3,Ayanda,\"Tokai"}
```

I suspect it may be tricky to fix because want to support newlines when using quotation marks `"`, I'm also aware that we should not put the quotation marks where we do not need them (unfortunately I don't control the creation of the CSV I'm working with).

Anyway, thought this may be helpful for someone else out there.

**Comment by tilo** [comment]
@simonrentzke the second data line is invalid CSV - the double-quote should be escaped in the input file, e.g.:

`2,Shamina,"Howard\"s Manus"`

when I process the first 3 data lines, I get this:

```
> data = SmarterCSV.process('/tmp/bad.csv')
 => [{:id=>1, :name=>"Sibu", :suburb=>"Vredehoek"}, {:id=>2, :name=>"Shamina", :suburb=>"Howard\"s Manus\"\n3,Ayanda,\"Tokai"}]
 ```
 I'll have a look in a bit

**Comment by tilo** [comment]
@simonrentzke check out version 1.13.0 that is coming out soon - it has a fix for this issue (unbalanced / unescaped quote_char)

**Comment by simonrentzke** [comment]
@tilo thanks for the fix! 

It seems to work nicely on a small data-set, but unfortunately on a large data-set say 150k rows, it still hangs because the [code](https://github.com/tilo/smarter_csv/commit/49b375d9ba60db84d6f5e93291788137eee95fa3#diff-5d711b438bc7827a2181c7e22e81ac8afff1bc396391b3fe1b035923af20f03fR109) seems to only fail at the end of the file, so it processes the rest of the file into one row.

I think this is a small edge case though - and I've worked around it. 

Thanks for the fix.
