### ISSUE TITLE
DuplicateHeaders error for SmarterCSV::Reader

### ISSUE THREAD

**Issue by Piioo** [tilo/smarter_csv#290]
Hello,

Im trying to add a test for my implementation where the DuplicateHeaders Error is raised, but it is not working.

Im using `SmarterCSV::Reader.new(file_path, key_mapping: header_mapping, file_encoding: 'bom|utf-8', chunk_size: 1, remove_empty_values: false)` to instantiate csv object. Im need the Reader because I need the original csv row for documentation.

When I add now a duplicate header to my test file, nothing happen. The Header gets a 2 on the end of his name.
This is because `options[:duplicate_header_suffix]` is not nil, but an empty string. i https://github.com/tilo/smarter_csv/blob/main/lib/smarter_csv/header_transformations.rb#L16

I think the problem is here https://github.com/tilo/smarter_csv/blob/main/lib/smarter_csv/options.rb#L21
Because of this never DuplicateHeaders error is raised

**Comment by tilo** [comment]
It’s a feature, not a bug! ™️

One of the main goals of smarterCSV is that it works in most cases. Because of this, I recently added a feature that automatically numbers duplicate headers.

**Comment by tilo** [comment]
I added this to the docs [just above this paragraph](https://github.com/tilo/smarter_csv/blob/main/docs/header_transformations.md#key-mapping)

**Comment by Piioo** [comment]
ok, Im only write this because here https://www.rubydoc.info/github/tilo/smarter_csv is writen:

```
NOTES on Duplicate Headers:
As a corner case, it is possible that a CSV file contains multiple headers with the same name.

If that happens, by default smarter_csv will raise a DuplicateHeaders error.
```

**Comment by tilo** [comment]
@Piioo thank you for pointing that out! I updated the docs
