### ISSUE TITLE
Processing files uploaded with file_field_tag

### ISSUE THREAD

**Issue by rept** [tilo/smarter_csv#33]
Hi,

Thanks for the gem, works great.  I have one problem however when trying to process uploaded files.  

I have this in my haml:
  = file_field_tag :file_categories

and afterwards I want to process that file.

I tried with:
clients_data = params[:file_categories].read
SmarterCSV.process(clients_data, ...

But I'm getting File name too long - "#","CA_ID","CA_Desc"

I searched all over the net but the only thing I could find was this user having the same problem:
http://stackoverflow.com/questions/21396527/smarter-csv-and-uploaded-csv-file

How can I process uploaded files (with file_field_tag) ?

Thanks in advance.

**Comment by Joshhaws** [comment]
Thank you! I had the same problem.

**Comment by vmvwebworks** [comment]
it also worked for example when you use a form with params[:csv] 👍
