### ISSUE TITLE
Feature Request: Custom converters

### ISSUE THREAD

**Issue by bleuse** [tilo/smarter_csv#41]
SmarterCSV definitely is a nice library to parse .csv files. A feature I am missing is a way of defining custom converters for some columns.
This can be seen as an extension of the `:convert_values_to_numeric` option. I am thinking of an option `:converters` that would take the list of converters to apply to which fields. This is similar to what the built-in CSV proposes but a bit different as it would allow to specify a converter for each field and not a sequence of converters to apply to each field.
Hope I'm clear enough.

**Comment by mauriciopasquier** [comment]
Any updates on this feature? I'm not familiar with smarter_csv code (I'm analizing it for a project) but it would be perfect for my use case :)

**Comment by toobulkeh** [comment]
:+1:

Some of my use cases:
1 Combining two fields into one:
```
last_name,first_name
JOE,BOB

=> name = JOE BOB
```
2 Data Manipulation
```
last_name,first_name
JOE,BOB

=> name = Joe Bob
```

3 Conditional Fields
```
row_type,organization,person
1,COMPANY,
2,,BOB

=> name = Company
=> name = Bob
```

**Comment by agarie** [comment]
This feature would be really neat. I don't have a lot of time right now, but if no one tackles it in the next weeks, I might be able to provide a pull request. :tada:

**Comment by tilo** [comment]
implemented in 1.1.0

**Comment by toobulkeh** [comment]
:+1:  just in time for our next release. Perfect, thanks!

**Comment by tilo** [comment]
@toobulkeh let me know how this implementation works for you.

I was debating if the converters should be provided by a custom class or by specifying a lambda
