### ISSUE TITLE
Typical performance for parsing?

### ISSUE THREAD

**Issue by netwire88** [tilo/smarter_csv#43]
What's the typical performance for parsing we should expect? I'm currently parsing rows in chunks of 3,000 rows but it's taking about 25-30 seconds (without inserting into database). Is that expected? 

So 1,000,000 rows should be about 166 minutes (or almost 3 hours) before any database inserts/updates are taken into account?

**Comment by toobulkeh** [comment]
That's probably completely dependent on your hardware. Though it would be nice to see a baseline for comparison between CSV tools (vanilla CSV, FasterCSV, SmarterCSV) https://www.ruby-toolbox.com/categories/CSV_Parsers

**Comment by toobulkeh** [comment]
Here's a 2007 report on the topic (showing useful benchmarking techniques):
http://blog.evanweaver.com/2007/09/29/not-invented-here/

**Comment by xjlin0** [comment]
Smarter_csv is fabulous!! 
I am hoping smarter_csv can start slice chunck without reading the entire csv file into the memory.  The ruby original CSV.each will read the entire csv file, but CSV.foreach only read line by line without reading the entire file.  In such way CSV.foreach can start much quicker and take less memory for huge csv files.  It'd be really cool if SmarterCSV.process can also do that.

**Comment by xjlin0** [comment]
Smarter_csv is a great gem! Save me ton's of time by parallel processing.

One possible improvement I am hoping here, is to let smarter_csv sending out the chunk before finishing reading the entire files.  Smarter_csv use readline to read each line, smartly avoiding reading the entire csv files into memory.  However the it seems  cannot sending chunk out before finishing the entire csv files.

**Comment by tilo** [comment]
good point @xjlin0 !! Will look into that!

**Comment by tilo** [comment]
check out this blog post by @xjlin0 : http://t.co/SlyBpfnSUV
