### ISSUE TITLE
Allow smarter_csv to output CSV

### ISSUE THREAD

**Issue by agarie** [tilo/smarter_csv#44]
Thanks for this wonderful library, I've been using it daily for a couple of weeks! The only problem so far is that it doesn't support writing CSV files. Are you interested in a pull request regarding this feature or is it something you definitely don't want in the library?

Thanks for your time.

**Comment by tilo** [comment]
punting on this feature for now

**Comment by tilo** [comment]
@agarie I'm adding this feature in the next release!

**Comment by tilo** [comment]
@agarie writing of CSV files is now available in version 1.11.0
