### ISSUE TITLE
Improper logic in guess_line_ending code

### ISSUE THREAD

**Issue by feens** [tilo/smarter_csv#47]
I noticed that the :auto line-ending function wasn't properly detecting \r\n endings, so I took a look at the code.

Here's the line that caught my attention:
next if quoted_char || c !~ /\r|\n|\r\n/

The whole block will never figure out "\r\n" because it's going through and looking for a "\r", "\n" or "\r\n" character, the problem being that "\r\n" is 2 characters.  

We've worked around this for now just by manually passing the line-ending, but figured I should mention it.

**Comment by tilo** [comment]
pull request welcome!

**Comment by tilo** [comment]
thanks for letting me know! this was introduced by someone else's PR. it's fixed in 1.1.0
