### ISSUE TITLE
Mapping keys to nested attributes?

### ISSUE THREAD

**Issue by jbschrades** [tilo/smarter_csv#51]
Are nested attributes supported in key_mapping?  I've tried several different ways but cannot get it to work. For instance, the following does not put the customer_attributes in the hash after SmarterCSV processing:

```
customer_attributes = Hash.new
options = {
        key_mapping: { 
            :shipping_name => customer_attributes[:name],
            :email => customer_attributes[:email]
       }
}
```

**Comment by tilo** [comment]
I'm not sure what you are trying to accomplish here.. 

`key_mapping` is a way to tell SmarterCSV how to map existing column names in a CSV file
into different strings or symbols you want to use instead of those column names.
