### ISSUE TITLE
Simplify the creation of CSV-handling CLI apps

### ISSUE THREAD

**Issue by agarie** [tilo/smarter_csv#56]
I'm writing lots of small programs in my current job for cleaning CSV data (dozens of services export CSV files in dozens of different ways...). Most of them require both CSV (for output) and SmarterCSV (for input) and map some operation in one or more columns, generating new ones.

It would be great if we could add some sort of functionality to SmarterCSV that simplified this process. For example, the file:

```
timestamp,old_column
1425945600,1
1425168000,5
```

Processed with the following "app":

``` ruby
require 'smarter_csv'

SmarterCSV.app(STDIN, STDOUT) do |row|
  row[:new_column_name] = row[:old_column] + 2
end
```

Would return the output:

``` sh
$ ./smarter-csv-app.rb < input-example.csv
timestamp,old_column,new_column_name
1425945600,1,3
1425168000,5,7
```

I'm implementing something similar locally. @tilo if you're interested (or if more people like the idea), I can send a pull request.

**Comment by tilo** [comment]
thanks @agarie. I'll think about it

**Comment by tilo** [comment]
I agree it would be great to have a command line tool! will try to cook something up. in 1.2.0 perhaps

**Comment by tilo** [comment]
@agarie can you send a pull request?

**Comment by tilo** [comment]
@agarie I'm closing this Issue, and am looking forward to your pull request
