### ISSUE TITLE
Skip real comments before header

### ISSUE THREAD

**Issue by xufeiyun** [tilo/smarter_csv#58]
my csv file may look like follows:

\# this is the comment line for csv file
\# this is also the meaningful lines for csv file
\# here shows the each field descriptions:
\# name: full name, code: like identity card no, mobile: telephone or mobile phone no
\# now below is the header WITHOUT # starts
name,code,mobile
eric,a001,10086

so what I want to do is that smarter csv should skip all those items those start with #, since they are all meaningful comments(at least for my stuff), which not only just the field comment like #name,code,mobile.

I would like to not allow setting the header comment chacater: # for your interace.

Yeah, another feature is about the exporting feature, maybe like SmarterCSV.export,
suggesting to change SmarterCSV.process to SmarterCSV.import.

What do you think?

Thanks
Eric

**Comment by tilo** [comment]
Hi Eric,
I don't understand your question.

if you want to ignore the comments, you can just set `{ :comment_regexp  =>   /^#/ }` , and SmarterCSV will ignore the comments.

**Comment by tilo** [comment]
Eric, this is a non-issue, because this is exactly what `{ :comment_regexp => /^#/ }` is supposed to do!
