### ISSUE TITLE
end of file reached

### ISSUE THREAD

**Issue by netwire88** [tilo/smarter_csv#59]
Hi,
For some CSV files, I'm getting `end of file reached` when reading CSV file. Has anyone seen this error before?

```
csv_options = { chunk_size: self.flush_limit, headers_in_file: false, col_sep: '|', row_sep: :auto, remove_empty_hashes: true, force_simple_split: true }
Zlib::GzipReader.open(file) do |csv|
              SmarterCSV.process(csv, csv_options) do |chunk|
              end
end
```

**Comment by agarie** [comment]
Can you post an example of a CSV file with this problem? This way we can reproduce the error and iterate on it.

**Comment by supremebeing7** [comment]
I get this error as well, and so far it seems to only happen when the CSV file is blank. Is there a way to control for this, other than rescuing this error in my app?

**Comment by netwire88** [comment]
Unfortunately I can't provide the CSV file due to privacy reasons, but here's my code. Any suggestions?

```
        csv_options = { chunk_size: self.flush_limit, headers_in_file: false, col_sep: '|', remove_empty_hashes: true, force_simple_split: true,
                        user_provided_headers: [
                            'external_id', 'name', 'counter', 'category'
                        ] }

   Zlib::GzipReader.open(file) do |csv|
          SmarterCSV.process(csv, csv_options) do |chunk|
              chunk.each do |row|
                 ...processing work..
              end
          end
   end
```

**Comment by tilo** [comment]
might be because you're unzip-ing the file.

reading from a file handle definitely works - this code works for me:

```
options = {headers_in_file: false, col_sep: '|', remove_empty_hashes: true, force_simple_split: true,
                        user_provided_headers: [
                            'external_id', 'name', 'counter', 'category'
                        ] }

data = []
File.open('/tmp/error.csv', 'r') do |handle|
   data = SmarterCSV.process( handle, options)
end

data
 => [{:external_id=>"HDR", :name=>196321, :counter=>"SUEXXE", :category=>"07/14/2015 07:06:56"}, {:external_id=>"data in pipe delimited format"}, {:external_id=>"TRL", :name=>3337}]
```

**Comment by tilo** [comment]
could this be caused by un-balanced quotes or double-quotes in your CSV file?

**Comment by tilo** [comment]
@netwire88 @agarie ping! can you provide an example, perhaps a gist with a file and code which loads it which reproduces the problem?

could this be caused by un-balanced quotes or double-quotes in your CSV file?

**Comment by cawel** [comment]
I also had this issue of `EOFError`, coupled with:
```
line contains uneven number of quote chars so including content of next line
```
My input file has a special character (`^A`, ascii #1) to separate columns. And as such, I really don't care about escaping. So I specified `quote_char: ''` in the `process` method and it worked fine.

**Comment by tilo** [comment]
ahh.. looks like iTunes dump format :)

**Comment by cawel** [comment]
Let's just say it does indeed have some similarities ;)

**Comment by tilo** [comment]
lol :)

**Comment by netwire88** [comment]
I also had the `line contains uneven number of quote chars so including content of next line` error only after processing in `verbose` mode. I used these options `force_simple_split: true, verbose: true, quote_char: '', strip_chars_from_headers: /[\-"]/` and now it's working. Very odd. Is there a way to skip headers but still provide custom headers?

**Comment by KevinColemanInc** [comment]
for future people, I had the same error, but the reason was because I was passing in a File and calling process twice.  If you call it a second time, the `File.read` returns an empty string, thus causing the error.

reload the file if you need to run parsing on the same file object twice

**Comment by 31piy** [comment]
I had a similar issue. My CSV file contained some binary characters. As soon as the library started to parse the file, it stopped the line containing binary characters. On further analysis, I found that the loop `while !f.eof?` was being terminated because it thought that end of file was reached.

For now, I had manually solved this problem by adding a `b` when opening a file, so that the file opens in binary mode.

Line#23 changed to `f = input.respond_to?(:readline) ? input : File.open(input, 'rb:options[:file_encoding]')`

**Comment by benalavi** [comment]
I had this issue and narrowed it down to a a single `"` quote in my CSV file. The message `line contains uneven number of quote chars so including content of next line` then makes sense with the `EOFError` as I assume it parsed the rest of the file looking to balance the quote and then ran out of file.

To fix I can change the quote char but to avoid confusion maybe it should catch EOF when trying to balance quotes and print an error about not being able to balance quotes.

**Comment by tilo** [comment]
Reaching EOF can happen when single or uneven number of quotes are encountered - those are often invalid CSV files.

**Comment by tilo** [comment]
Reaching EOF can also happen as a result of newline characters in the header row
