### ISSUE TITLE
New lines in CSV file

### ISSUE THREAD

**Issue by bcackerman** [tilo/smarter_csv#61]
``` csv
billing_address_street1,billing_address_street2,billing_address_city,billing_address_state,billing_address_zip,phone,fax,email
Jordan,Longtime,North Shore Gym,,,,,,"200 W. Canal St.
",,chicago,Illinois,660-362-4476,,drjordan@example.com
```

I have some users importing CSV files which have new lines & formatting in the cells.  This messes up the parsing `smarter_csv` does.  Any tips or is this a bug?

**Comment by tilo** [comment]
this looks like your CSV files might be invalid.

You may want to examine your CSV files and check if there is a specific character sequence you can use as :row_sep -- or you might want to try `{:row_sep => :auto}` in the options

**Comment by bcackerman** [comment]
Ended up going back to using Ruby's CSV library and things worked again. Thanks though!

**Comment by chrisnicola** [comment]
It isn't invalid the new line is in a quoted string.

**Comment by tilo** [comment]
Will need to think of how to best fix/address this, and keep the parsing fast.
Never saw new lines in CSV fields before

**Comment by chrisnicola** [comment]
@tilo technically any string could be valid inside quotes afaik, and escaped quotes are represented by a double-quote. 

https://en.wikipedia.org/wiki/Comma-separated_values#General_functionality

Perhaps allow the library to be configured to sacrifice speed vs. parsing robustness. I agree that most CSVs should not need this feature.

**Comment by chrisnicola** [comment]
If it matters I've noticed the built in Ruby CSV library also seems to fail to handle this properly even thought it seems like it should. I've been debating opening a bug for that as well.

**Comment by webattitude** [comment]
+1

**Comment by chrisnicola** [comment]
Any more thoughts or progress on this? I'm willing to attempt a pull request if no one else has time.

**Comment by jbittencourt** [comment]
+1

**Comment by Timmitry** [comment]
What worked for me is to really use a newline in the CSV

```csv
Header 1;Header 2
Column 1 Row 1;Column 2 Row 1
Column 1
Row 2; Column 2 Row 2
```

This will yield "Column 1\nRow 2" in the parsed hash. However, I'd also be interested in a possibility to have newline characters in a quoted string!

**Comment by tilo** [comment]
Closing this issue:

* quoted fields with new line in them are supported in recent versions of smarter_csv
* double-quotes inside quoted fields are also supported, to represent a single quote character, as in 3"

One exception: 

newline characters in the header are not supported
