### ISSUE TITLE
Feature Request: Start and End Row / Offset?

### ISSUE THREAD

**Issue by rubyguy** [tilo/smarter_csv#62]
Hi , thanks for this nice intelligent parser. However, one feature that I would love to see is Start Row & off set combination which will make parsing specific parts of CSV very easy.

**Comment by tilo** [comment]
version 1.1.1 added an option to skip_lines at the beginning of the CSV file

**Comment by lastobelus** [comment]
a "skip lines without skipping headers" would be useful (examples: rerunning a partially completed worker or re-running an import after fixing a malformed line

**Comment by 9mm** [comment]
yes, a skip line feature seems useless if it is only counting before the CSV headers (who does this?). The real use of skipping lines is partial processing of CSVs (like a daily batched CSV and were processing the current CSV and there is no unique index column in the CSV)
