### ISSUE TITLE
:headers_in_file option does not work 

### ISSUE THREAD

**Issue by innhyu** [tilo/smarter_csv#64]
Hi, this seems to happen for all csv files..
Files that are run with :headers_in_file => false 
seems to fail with the exact same error every time.

NoMethodError: undefined method `map!' for nil:NilClass
	from /Users/innhyu/.rvm/gems/ruby-2.1.6/gems/smarter_csv-1.0.19/lib/smarter_csv/smarter_csv.rb:64:in `process'
	from (irb):1
	from /Users/innhyu/.rvm/gems/ruby-2.1.6/gems/railties-4.1.8/lib/rails/commands/console.rb:90:in `start'
	from /Users/innhyu/.rvm/gems/ruby-2.1.6/gems/railties-4.1.8/lib/rails/commands/console.rb:9:in `start'
	from /Users/innhyu/.rvm/gems/ruby-2.1.6/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/innhyu/.rvm/gems/ruby-2.1.6/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/innhyu/.rvm/gems/ruby-2.1.6/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by pablocrivella** [comment]
+1

**Comment by tilo** [comment]
If you set `:headers_in_file => false` , you MUST provide an array of `user_provided_headers`, 
e.g. `options = {:headers_in_file => false, :user_provided_headers => [:a,:b,:c,:d,:e,:f]}`

```
> data = SmarterCSV.process 'spec/fixtures/no_header.csv', options
 => [{:a=>"Dan", :b=>"McAllister", :c=>2, :d=>0}, {:a=>"Lucy", :b=>"Laweless", :d=>5, :e=>0}, {:a=>"Miles", :b=>"O'Brian", :c=>0, :d=>0, :e=>0, :f=>21}, {:a=>"Nancy", :b=>"Homes", :c=>2, :d=>0, :e=>1}, {:a=>"Hernán", :b=>"Curaçon", :c=>3, :d=>0, :e=>0}]

```

**Comment by tilo** [comment]
will add an error message, complaining about missing option :user_provided_headers in the next version

**Comment by netwire88** [comment]
If I have a header in a file, and I want to skip the header and provide my own list of `user_provided_headers`, how should I configure options? I tried it with `headers_in_file: false` but it complained the number of headers in file didn't match the number of headers provided.
