### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8 

### ISSUE THREAD

**Issue by Nitin-Salunke** [tilo/smarter_csv#76]
I get the exception **ArgumentError: invalid byte sequence in UTF-8** when I try to process a CSV.
Is there some way to deal with it in smarter CSV ? or I have to filter out the invalid byte sequence first and then process it with smarter CSV ?

**Comment by damenez** [comment]
Also having the same issue above...Kindly share if you have a fix. Thank you!

**Comment by Nitin-Salunke** [comment]
@damenez I had to clean the entire file before processing it, did not find a better solution to fix it.

**Comment by Shwetakale** [comment]
@Nitin-Salunke @damenez I had also came to similar issue. I will check how to fix this in gem but instead of fixing rows manually I just wrote code which will tell me about bad rows by using following snippet

      handler = open(suppression_file)
      csv_string = handler.read.encode!("UTF-8", "utf-8", invalid: :replace, replace: 'bad encoded row')
      data = CSV.parse(csv_string, {headers: true, header_converters: :symbol})

Now row which contains 'bad encoded row' is a row which I have to remove.

**Comment by tilo** [comment]
1.1.1 should fix this - you can now force-encode to UTF-8

1.1.1 is replacing invalid UTF-8 sequences with ''

**Comment by siruguri** [comment]
In case someone lands here with a Google search, the relevant commit appears to be https://github.com/tilo/smarter_csv/commit/84cbdebd415ad0b06a72c8280a9842da1d6efc12, and the option key is `:force_utf8`

**Comment by turnspike** [comment]
To build on the answer from @siruguri the full command is: ```data = SmarterCSV.process(file_uri, force_utf8: true)```
