### ISSUE TITLE
Stream is not closed

### ISSUE THREAD

**Issue by 31piy** [tilo/smarter_csv#78]
I have a case in which:
1. I have 10 zip files, each containing some csv files.
2. For each zip file, I will make a temp folder and extract the contents to that folder.
3. For each csv file in temp folder, I use SmarterCSV to parse its contents.
4. I delete the temp folder after a zip file has been processed completely.

The issue is, when I try to delete that folder using `FileUtils.remove_entry_secure` method, it throws an error saying that the directory is not empty. If I comment out SmarterCSV related code, the folders are being created, the files are being extracted, and the temp folders are being deleted successfully.

I tried to look into the SmarterCSV library file, and found that the files are not being closed after reading. When I appended a statement `f.close` before `$/ = old_row_sep` in the `ensure` block of `smarter_csv.rb`, everything worked fine.

**Comment by tabunmuri** [comment]
👍

**Comment by tilo** [comment]
1.1.1 should fix this
