### ISSUE TITLE
CSV::IllegalFormatError thrown when parsing CSV with double quotes around column names and values

### ISSUE THREAD

**Issue by xenover** [tilo/smarter_csv#81]
Hello!

Basically the title. I was trying to parse a file that is using double quotes and the quote character i.e.

"column1","column2"
"value1","value2"

but it kept throwing the CSV::IllegalFormatError.

I also tried using CSV.parse without the :quote_char parameter and that works fine.

Using OSX 10.11.4 on Macbook Pro Retina 13" Early 2013 and Ruby 1.8.7 (Rails 2.3.18).

Thanks!

**Comment by tilo** [comment]
I think this should be working in 1.1.4

**Comment by tilo** [comment]
@xenover can you try with the latest version of smarter_csv ?

**Comment by tilo** [comment]
fixed in 1.1.4
