### ISSUE TITLE
Documentation should illustrate use-case of key mappings + value converters

### ISSUE THREAD

**Issue by armahillo** [tilo/smarter_csv#84]
Spent 2 hours pulling my hair out over this, thinking the error was caused by something else.

If you are using mappings AND value converters, the value converters hash should be keyed based on the MAPPED field name, NOT the CSV header field name.

For example, if your CSV has headers of "name, age" and you do

`:key_mapping => { :name => :full_name, :age => :age }`

and you want to have the :name run through a converter that makes it all uppercase (class FullNameConverter), you need to do it like this:

`:value_converters => { :full_name => FullNameConverter }`

This is not apparent from the example given in the docs, nor is it obvious from the output of running it with the incorrect fields specified. (ie. specifying ":name => FullNameConverter" in that example)

**Comment by tilo** [comment]
Thank you! Updated doc.
