### ISSUE TITLE
Feature Request: Allow SmarterCSV to accept a CSV string loaded in memory. 

### ISSUE THREAD

**Issue by larquin** [tilo/smarter_csv#87]
In the case of managing CSV data in environments with ephemeral file systems, would it make sense to allow for an option to load the CSV into memory? 

The standard ruby CSV library allows for in memory parsing of CSV files, but SmarterCSV only seems to allow for a file input. I'd like to be able to leverage all of the nice options available with SmarterCSV, even when I don't have the luxury of being able to store a file on my actual server. 

Thoughts?

**Comment by tilo** [comment]
I'll look into it - pull requests are always welcome

**Comment by wtfiwtz** [comment]
Why don't you use `StringIO`? Unfortunately this sort of thing isn't very efficient with memory... but I am already using this in production today (with SmarterCSV).

**Comment by tilo** [comment]
generally it is not a good idea to try to hold the CSV data in memory - if the CSV file is large, then you just end up allocating a lot of memory which is not really needed all at once - it is more efficient to read in the file on the fiy, or in chunks.

**Comment by larquin** [comment]
Sure, but if you're managing those chunks yourself,  it seems doable. Ultimately using `StringIO` for my purposes seems to make a lot of sense, so I'm closing this one. Thanks!
