### ISSUE TITLE
ERROR -- : end of file reached (EOFError) with some CSV files

### ISSUE THREAD

**Issue by katiemccann** [tilo/smarter_csv#90]
Using 1.1.4, I'm getting an EOFError on some .csv files. I've attached an example (had to zip it as github won't accept a csv attachment).[linkedin_test.csv.zip](https://github.com/tilo/smarter_csv/files/737781/linkedin_test.csv.zip)

Error looks like:
[2017-01-28T14:02:39.334602 #41155] ERROR -- : end of file reached (EOFError)
/Users/katiemccann/.rvm/gems/ruby-2.3.1/gems/smarter_csv-1.1.4/lib/smarter_csv/smarter_csv.rb:42:in `readline'
/Users/katiemccann/.rvm/gems/ruby-2.3.1/gems/smarter_csv-1.1.4/lib/smarter_csv/smarter_csv.rb:42:in `process'
/Users/katiemccann/Documents/Code/recommender/app/controllers/contacts_controller.rb:92:in `block in linkedin_upload'

Line 92 of contacts_controller.rb:
li_contacts = SmarterCSV.process(filename, {:verbose => true, :force_utf8  =>true, :key_mapping => {:e_mail_address => :email}})

I’ve tried playing around with the encoding but no matter what, I get this EOFError

**Comment by noma4i** [comment]
possible issue with quotes. For me it was solved by adding `quote_char: "'"`

**Comment by katiemccann** [comment]
Unfortunately, the quot_char is not my issue.

**Comment by tilo** [comment]
Hey @katiemccann is  `row_sep`  set correctly? 
Another issue could be non-escaped or incorrectly nested quote characters.

It would be best if  you could provide a minimal CSV file which reproduces the problem

**Comment by katiemccann** [comment]
Hi @tilo, The file is attached to my original post (linkedin_test.csv.zip). It's not an issue with row_sup or any other characters in the file. I can explain in more detail the steps to reproduce this:

1. Download a file of my contacts from LinkedIn: https://www.linkedin.com/addressBookExport (saving as Microsoft Outlook .csv format)
2. The original file saved in step 1 imports just fine.
3. Open the file in Text Edit on a Mac (or Excel and resave as .csv). Make ANY little edit to the file, even a single character edit, remove lines, etc. and save.
4. Try to import the edited version of the file that's saved in step 3 (which is what I've attached in my original post), it gives the EOFError.

**Comment by tilo** [comment]
downloading the contacts doesn't seem to work for me - can you provide a sample file?

**Comment by katiemccann** [comment]
It's in my original post, can you not access it?

**Comment by tilo** [comment]
I downloaded the file, but it still worked after saving it with TextEdit

**Comment by katiemccann** [comment]
You can parse that exact file without the EOFError? What params are you passing into the process method? I'm attempting to parse it as:  SmarterCSV.process(filename, {:verbose => true, :force_utf8 =>true, :key_mapping => {:e_mail_address => :email}})

**Comment by katiemccann** [comment]
FYI the latest updates from a couple of months ago have solved this issue for me, so will close it. Thanks!
