### ISSUE TITLE
Key mapping with procs?!

### ISSUE THREAD

**Issue by RST-J** [tilo/smarter_csv#98]
Hi,
I quite wasted some time now until I finally started to look into the code - surprisingly this quickly helps ...

For what its worth, I s a hash which maps headers from the CSV file to keys in the result hash       truggled with key mapping. In the docs key mapping is explained like this:
>   a hash which maps headers from the CSV file to keys in the result hash

To my not least surprise, this is not happening - at least to how I intuitively interpreted 'header from the CSV file'
```ruby
2.3.1 :010 > SmarterCSV.process StringIO.new("MiniMal\na"), key_mapping: {MiniMal: :foo}
 => [{:minimal=>"a"}]
```
How it works is by mapping `:minimal` (which again surprises me in Rubyland, I'd rather expected `:mini_mal` in this case).

Whatever, that's only what I encountered along the way. I basically wanted to map keys sort of dynamically which I implemented by util functions so far. But, wouldn't it be nice, if smarter_csv called the key_mapping for each key, if its value is not a hash but some callable?

**Comment by tilo** [comment]
Thank you for the feedback, RST-J ! Very valuable! I'll look into that, and will also look at improving the README.

**Comment by tilo** [comment]
Hey @RST-J : I'm planning re-writing SmarterCSV to support Procs for transforming headers, data, and validations. 

Please leave your comments here: 
https://github.com/tilo/smarter_csv/issues/118
