### ISSUE TITLE
strip_chars_from_headers options not removing pipe character (|) from header

### ISSUE THREAD

**Issue by k-akarsh** [tilo/smarter_csv#99]
Entering the regex  /[|öäüß\/\(\)\-.%]/ for :strip_chars_from_headers option is working for all characters except the pipe character (|).
The field in the header of the csv is:  No. | Sku No. where the pipe character is not getting removed.
The regex works for this in plain ruby.

**Comment by tilo** [comment]
when I cut+paste the code for your regular expression, it looks like it's all Unicode.
Make sure your `|` character is ASCII encoded, not Unicode.
